Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -28,10 +28,13 @@ jobs:
           cache: npm
       
       - name: Install dependencies
-        run: npm install
+        run: npm install --no-package-lock
       
       - name: Build
         run: npm run build
+      
+      - name: List output files (debug)
+        run: ls -la ./out || echo "Out folder not found"
       
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
